### ISSUE TITLE
Mandelbrot only `Terrible` works

### ISSUE THREAD

**Issue by rroelz** [SchardtS/ProjectTemplate#3]
I'm probably doing this wrong but only the "Terrible" Mandelbrot code gives me a graphic output. The others don't seem to do anything? Or maybe they do? 
If I call them from the `Code/` directory I get the following Stacktrace: 
```text
Traceback (most recent call last):
  File "MandelbrotCode_(Uncommented).py", line 41, in <module>
    plot_mandelbrot(x, y)
  File "MandelbrotCode_(Uncommented).py", line 33, in plot_mandelbrot
    plt.savefig('Results/Figures/Mandelbrot.png', facecolor=None)
  File "/home/robin/.local/lib/python3.8/site-packages/matplotlib/pyplot.py", line 958, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/robin/.local/lib/python3.8/site-packages/matplotlib/figure.py", line 3019, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/robin/.local/lib/python3.8/site-packages/matplotlib/backends/backend_qtagg.py", line 85, in print_figure
    super().print_figure(*args, **kwargs)
  File "/home/robin/.local/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2319, in print_figure
    result = print_method(
  File "/home/robin/.local/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 1648, in wrapper
    return func(*args, **kwargs)
  File "/home/robin/.local/lib/python3.8/site-packages/matplotlib/_api/deprecation.py", line 412, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/home/robin/.local/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 541, in print_png
    mpl.image.imsave(
  File "/home/robin/.local/lib/python3.8/site-packages/matplotlib/image.py", line 1675, in imsave
    image.save(fname, **pil_kwargs)
  File "/home/robin/.local/lib/python3.8/site-packages/PIL/Image.py", line 2297, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: 'Results/Figures/Mandelbrot.png'
```
But I guess that's because it's supposed to be run from the main folder? 
Do they write into `Results/Figures` and overwrite the already present figures there?

**Comment by SchardtS** [comment]
Your guess is correct. For some reason on my system the current working directory is always "ProjectTemplate" instead of "ProjectTemplate/Code". I'm still trying to find out why this actually happens.
